name: 'Add/update PR comment'
description: |
  Add a comment to PR that called this action.
  Can only be called from a workflow triggered from a PR and not from a closing PR action.
author: 'Direktoratet for samfunnssikkerhet og beredskap'
inputs:
  pr-comment-text:
    description: Body of comment to add to PR.
    required: true
  delete-comments-starting-with:
    description: |
      CAUTION: Comments on the PR starting with this string will be deleted.
      Use this if your comment should supersede a previous comment.
      If left empty no comments will be deleted.
    default: ''
    required: false
  github-repo-token:
    description: Github repo token is required by for Adding comments from actions to github PRs.
    required: true
runs:
  using: 'composite'
  steps:
    - name: 🦕 Deno install
      shell: bash
      run: deno install
      working-directory: ${{ github.action_path }}/../

    - id: check-pull-request
      shell: bash
      run: deno run --allow-read --allow-write --allow-env ${{ github.action_path }}/action/1_check-pull-request.ts

    - id: log-inputs
      shell: bash
      env:
        INPUT_PR_COMMENT_TEXT: '${{ inputs.pr-comment-text }}'
        INPUT_DELETE_COMMENTS_STARTING_WITH: '${{ inputs.delete-comments-starting-with }}'
      run: deno run --allow-read --allow-write --allow-env ${{ github.action_path }}/action/2_log-inputs.ts

    - id: add-comment
      shell: bash
      env:
        INPUT_NEW_COMMENT_BODY: ${{ inputs.pr-comment-text }}
        INPUT_DELETE_COMMENTS_WITH_PREFIX: ${{ inputs.delete-comments-starting-with }}
        INPUT_GITHUB_REPO_TOKEN: ${{ inputs.github-repo-token }}
      run: deno run --allow-read --allow-write --allow-env --allow-net ${{ github.action_path }}/action/3_add-comment.ts
