name: 'Delete ephemeral PR image repository from ACR'
description: |
  Use Azure CLI to delete images from docker registry (ACR).
author: 'Peder Schmedling'
inputs:
  dsb-build-envs:
    description: 'DSB build environment variables JSON.'
    required: true
runs:
  using: 'composite'
  steps:
    - shell: bash
      run: |
        # Check if triggered by pull request event
        [ ! '${{ github.event_name }}' == 'pull_request' ] \
          && echo 'ERROR: delete-pr-images-from-acr: This action should only be called by pull request events.' \
          && EXIT_CODE=1 \
          || EXIT_CODE=0
        exit ${EXIT_CODE}

    # we need to verify inputs since they are optional input to create-build-envs action
    - uses: dsb-norge/github-actions/ci-cd/require-build-envs@v1.5
      with:
        dsb-build-envs: ${{ inputs.dsb-build-envs }}
        require: |
          acr-service-principal
          docker-image-registry
          docker-image-repo
          application-image-name

    # log into Azure CLI with service principal
    - uses: azure/login@v1.5
      with:
        creds: ${{ fromJSON(inputs.dsb-build-envs).acr-service-principal }}
        allow-no-subscriptions: true

    - shell: bash
      run: |
        # Delete PR image repository from ACR
        az acr repository delete \
          --name ${{ fromJSON(inputs.dsb-build-envs).docker-image-registry }} \
          --repository ${{ fromJSON(inputs.dsb-build-envs).docker-image-repo }}/${{ fromJSON(inputs.dsb-build-envs).application-image-name }} \
          --yes \
          && echo 'delete-pr-images-from-acr: Successfully deleted "${{ fromJSON(inputs.dsb-build-envs).docker-image-registry }}/${{ fromJSON(inputs.dsb-build-envs).docker-image-repo }}/${{ fromJSON(inputs.dsb-build-envs).application-image-name }}"' \
          && EXIT_CODE=0 \
          || echo 'delete-pr-images-from-acr: Unable to delete "${{ fromJSON(inputs.dsb-build-envs).docker-image-registry }}/${{ fromJSON(inputs.dsb-build-envs).docker-image-repo }}/${{ fromJSON(inputs.dsb-build-envs).application-image-name }}"' \
          || EXIT_CODE=0

        # log out of azure CLI
        az account clear

        exit ${EXIT_CODE}
