name: "Delete ephemeral PR image repository from ACR"
description: |
  Use Azure CLI to delete images from docker registry (ACR).
author: "Peder Schmedling"
inputs:
  dsb-build-envs:
    description: |
      DSB build environment variables JSON.
      Required fields:
        See first step.
      Optional fields:
        None.
    required: true
runs:
  using: "composite"
  steps:
    # we need to verify inputs since they are optional input to create-build-envs action
    - uses: dsb-norge/github-actions/ci-cd/require-build-envs@v3
      with:
        dsb-build-envs: ${{ inputs.dsb-build-envs }}
        require: |
          acr-service-principal
          docker-image-registry
          docker-image-repo
          application-image-name

    - id: check-pull-request
      shell: bash
      run: |
        # Check if triggered by pull request event

        set -o allexport; source "${{ github.action_path }}/helpers.sh"; set +o allexport;

        [ ! '${{ github.event_name }}' == 'pull_request' ] \
          && log-error 'This action should only be called by pull request events.' \
          && EXIT_CODE=1 \
          || EXIT_CODE=0
        exit ${EXIT_CODE}

    # log into Azure CLI with service principal
    - uses: azure/login@v2
      with:
        creds: ${{ inputs.dsb-build-envs && fromJSON(inputs.dsb-build-envs).acr-service-principal }}
        allow-no-subscriptions: true

    - id: delete-pr-image-repo
      shell: bash
      run: |
        # Delete PR image repository from ACR

        set -o allexport; source "${{ github.action_path }}/helpers.sh"; set +o allexport;

        az acr repository delete \
          --name ${{ fromJSON(inputs.dsb-build-envs).docker-image-registry }} \
          --repository ${{ fromJSON(inputs.dsb-build-envs).docker-image-repo }}/${{ fromJSON(inputs.dsb-build-envs).application-image-name }} \
          --yes \
          && log-info 'Successfully deleted "${{ fromJSON(inputs.dsb-build-envs).docker-image-registry }}/${{ fromJSON(inputs.dsb-build-envs).docker-image-repo }}/${{ fromJSON(inputs.dsb-build-envs).application-image-name }}"' \
          && EXIT_CODE=0 \
          || log-info 'Unable to delete "${{ fromJSON(inputs.dsb-build-envs).docker-image-registry }}/${{ fromJSON(inputs.dsb-build-envs).docker-image-repo }}/${{ fromJSON(inputs.dsb-build-envs).application-image-name }}"' \
          || EXIT_CODE=0

        # log out of azure CLI
        az account clear

        exit ${EXIT_CODE}
