name: 'Delete ephemeral PR image repository from ACR'
description: |
  Use Azure CLI to delete images from docker registry (ACR).
author: 'Direktoratet for samfunnssikkerhet og beredskap'
inputs:
  dsb-build-envs:
    description: |
      DSB build environment variables JSON.
      Required fields:
        See first step.
      Optional fields:
        None.
    required: true
runs:
  using: 'composite'
  steps:
    # we need to verify inputs since they are optional input to create-build-envs action
    # TODO revert to @v4
    - uses: dsb-norge/github-actions/ci-cd/require-build-envs@git-lock
      with:
        dsb-build-envs: ${{ inputs.dsb-build-envs }}
        require: |
          acr-tenant-id
          acr-subscription-id
          acr-delete-service-principal-id
          docker-image-registry
          docker-image-repo
          application-image-name

    # log into Azure for ACR access (delete)
    - name: "🔑 Login to Azure"
      uses: azure/login@v2
      with:
        tenant-id: ${{ fromJSON(inputs.dsb-build-envs).acr-tenant-id }}
        subscription-id: ${{ fromJSON(inputs.dsb-build-envs).acr-subscription-id }}
        client-id: ${{ fromJSON(inputs.dsb-build-envs).acr-delete-service-principal-id }}

    - name: 🦕 Deno install
      shell: bash
      run: deno install
      working-directory: ${{ github.action_path }}/../

    - id: delete-acr-repo
      shell: bash
      run: deno run --allow-env --allow-read --allow-run=az ${{ github.action_path }}/action/1_delete_acr_repo.ts
      env:
        INPUT_DSB_BUILD_ENVS: ${{ inputs.dsb-build-envs }}
