name: 'Build a Python project'
description: |
  Given the required input this action configures the specified version of python and builds a given project.
  As for working directory the field 'application-source-path' of 'dsb-build-envs' should point to the base directory of the project.
author: 'Direktoratet for samfunnssikkerhet og beredskap'
inputs:
  dsb-build-envs:
    description: |
      DSB build environment variables JSON.
      Required fields:
        See first step.
      Optional fields:
        python-build-project-custom-command-pre-install
        python-build-project-custom-command-pre-lint
        python-build-project-custom-command-final
    required: true
runs:
  using: 'composite'
  steps:
    # verify we have required inputs in order to avoid blank labels/tags
    - uses: dsb-norge/github-actions/ci-cd/require-build-envs@v3
      with:
        dsb-build-envs: ${{ inputs.dsb-build-envs }}
        require: |
          python-version
          application-source-path

    - name: 🦕 Deno install
      shell: bash
      run: deno install
      working-directory: ${{ github.action_path }}/../

    - id: work-dir
      shell: bash
      env:
        INPUT_DSB_BUILD_ENVS: '${{ inputs.dsb-build-envs }}'
        GITHUB_WORKSPACE: '${{ github.workspace }}'
      run: deno run --allow-env --allow-read --allow-write ${{ github.action_path }}/action/1_work-dir.ts

    # set up Python
    - name: Set up Python 🐍
      uses: actions/setup-python@v4
      with:
        python-version: ${{ fromJSON(inputs.dsb-build-envs).python-version }}

    - id: python-build
      shell: bash
      working-directory: '${{ steps.work-dir.outputs.abs-path }}'
      env:
        INPUT_DSB_BUILD_ENVS: '${{ inputs.dsb-build-envs }}'
      run: |
          deno run \
          --allow-env \
          --allow-read \
          --allow-write \
          --allow-run \
          ${{ github.action_path }}/action/2_python-build.ts
