name: 'Delete GitHub caches created from a PR branch'
description: |
  This action deletes all GitHub caches created from a PR branch.
  This is to force deletion of caches overriding default cache eviction policy.
  Due to branch scope restrictions of GitHub caches, caches created from a non-default branch are not available
  from other branches, so we might as well delete them when the PR branch is merged to ensure default branch is
  not thrashing.

  This action will fail if not called from a 'pull_request' event with 'closed' action.

  Overriding default cache eviction policy:
    https://github.com/actions/cache/blob/704facf57e6136b1bc63b828d79edcd491f0ee84/tips-and-workarounds.md#force-deletion-of-caches-overriding-default-cache-eviction-policy
  Branch scope restriction:
    https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache
author: 'Direktoratet for samfunnssikkerhet og beredskap'
inputs:
  dsb-build-envs:
    description: |
      DSB build environment variables JSON.
      Required fields:
        See first step.
      Optional fields:
        None.
    required: true
runs:
  using: 'composite'
  steps:
    # we need to verify inputs since they are optional input to create-build-envs action
    - id: check-input
      uses: dsb-norge/github-actions/ci-cd/require-build-envs@v3
      with:
        dsb-build-envs: ${{ inputs.dsb-build-envs }}
        require: |
          github-dependencies-cache-pr-base-key

    - name: 🦕 Deno install # Added Deno install step
      shell: bash
      run: deno install
      working-directory: ${{ github.action_path }}/../ # Assuming common root for deno.json

    - id: delete-caches # Changed step ID and run command
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }} # Pass GH_TOKEN
        INPUT_DSB_BUILD_ENVS: ${{ inputs.dsb-build-envs }} # Pass DSB build envs
      run: deno run --allow-read --allow-env --allow-net --allow-run=gh ${{ github.action_path }}/action/1_delete_caches.ts # Run the Deno script
