name: 'Directory re-creator'
description: |
  USE WITH CAUTION!
  This action removes and re-creates a directory including all files and sub-directories within.
  If no directory is specified, the github.workspace directroy will be used.
author: 'Peder Schmedling'
inputs:
  directory:
    description: 'The directory to remove and re-create.'
    required: false
    default: '${{ github.workspace }}'
  recreate:
    description: 'If the directory should be recreated or not.'
    required: false
    default: 'true'
runs:
  using: 'composite'
  steps:
    - shell: bash
      run: |
        echo '::group::List directory contents before cleanup'
        if [[ ! -d "${{ inputs.directory }}" ]]
        then
          echo 'The directory "${{ inputs.directory }}" does not exist, nothing to delete.'
          echo '::endgroup::'
        else
          ls -lah '${{ inputs.directory }}'
          echo '::endgroup::'
          echo '::group::Perform Delete'
          echo 'Deleting directory: "${{ inputs.directory }}"'
          rm -rf '${{ inputs.directory }}'
          echo '::endgroup::'
        fi
        if [[ ! "${{ inputs.recreate }}" == "false" ]]
        then
          echo '::group::Create directory'
          echo 'Creating directory: "${{ inputs.directory }}"'
          mkdir -m u=rwx,go= '${{ inputs.directory }}'
          echo '::endgroup::'
        fi
