name: 'Directory re-creator'
description: |
  USE WITH CAUTION!
  This action removes and re-creates a directory including all files and sub-directories within.
  If no directory is specified, the github.workspace directroy will be used.
author: 'Peder Schmedling'
inputs:
  directory:
    description: 'The directory to remove and re-create.'
    required: false
    default: '${{ github.workspace }}'
  recreate:
    description: 'If the directory should be recreated or not.'
    required: false
    default: 'true'
runs:
  using: 'composite'
  steps:
    - id: re-create
      shell: bash
      run: |
        # Delete and re-create ${{ inputs.directory }}

        set -o allexport; source "${{ github.action_path }}/helpers.sh"; set +o allexport;

        start-group 'List directory contents before cleanup'
        if [[ ! -d "${{ inputs.directory }}" ]]
        then
          echo 'The directory "${{ inputs.directory }}" does not exist, nothing to delete.'
          end-group
        else
          ls -lah '${{ inputs.directory }}'
          end-group
          start-group 'Perform Delete'
          log-info 'Deleting directory: "${{ inputs.directory }}"'
          rm -rf '${{ inputs.directory }}'
          end-group
        fi
        if [[ ! "${{ inputs.recreate }}" == "false" ]]
        then
          start-group 'Create directory'
          log-info 'Creating directory: "${{ inputs.directory }}"'
          mkdir -m u=rwx,go= '${{ inputs.directory }}'
          end-group
        fi
