name: 'Notify Internal Status'
description: 'Send status update to internal API for CI/CD observability.'
author: 'Direktoratet for samfunnssikkerhet og beredskap'
inputs:
  status:
    description: 'Status to report (e.g. started, success, failure, running_step).'
    required: true
  step-name:
    description: 'Optional name of the step being reported.'
    required: false
  extra-data:
    description: 'Optional JSON string with additional data.'
    required: false
    default: '{}'
  application-name:
    description: 'Name of the application (from matrix/app-vars). Optional, but recommended.'
    required: false
  appvars:
    description: 'Optional APPVARS for fallback extraction.'
    required: false
  basic-auth-password:
    description: 'Password for basic auth to internal API.'
    required: true
runs:
  using: 'composite'
  steps:
    - name: 🦕 Deno install
      shell: bash
      run: deno install
      working-directory: ${{ github.action_path }}/../
    - id: notify-status
      shell: bash
      env:
        INPUT_STATUS: ${{ inputs.status }}
        INPUT_STEP_NAME: ${{ inputs['step-name'] }}
        INPUT_EXTRA_DATA: ${{ inputs['extra-data'] }}
        INPUT_APPLICATION_NAME: ${{ inputs['application-name'] }}
        INPUT_APPVARS: ${{ inputs.appvars }}
        INPUT_BASIC_AUTH_PASSWORD: ${{ inputs['basic-auth-password'] }}
        GITHUB_RUN_ATTEMPT: ${{ github.run_attempt }}
      run: |
        deno run \
          --allow-env --allow-net --allow-read \
          ${{ github.action_path }}/action/1_notify_status.ts
