name: 'Restore build dependencies cache from GitHub cache'
description: |
  Restores build dependencies cache from GitHub cache.
  Given a path, cache key and cache restore keys this will attempt to restore a cache.
  Before restore the given path is wiped clean.
  If the cache identified by the given cache key does not exist, the given cache restore keys will be used to look for other caches to restore.
  If the cache identified by the given cache key exist, the output 'cache-hit' is set to 'true'
author: 'Direktoratet for samfunnssikkerhet og beredskap'
inputs:
  dsb-build-envs:
    description: |
      DSB build environment variables JSON.
      Required fields:
        See first step.
      Optional fields:
        None.
    required: true
outputs:
  cache-hit:
    description: A boolean value to indicate an exact match was found for the key.
    value: ${{ steps.cache-restore.outputs.cache-hit }}
  cache-normalized-path:
    description: |
      The path to where the cache potentially is restored.
      This is the input 'github-dependencies-cache-path' normalized and with environment variables expanded.
    value: ${{ steps.resolve-path.outputs.cache-abs-path }}
runs:
  using: 'composite'
  steps:
    - name: 🦕 Deno install
      shell: bash
      run: deno install
      working-directory: ${{ github.action_path }}/../

    - id: check-input
      # TODO revert to @v3
      uses: dsb-norge/github-actions/ci-cd/require-build-envs@passwordless
      with:
        dsb-build-envs: ${{ inputs.dsb-build-envs }}
        require: |
          github-dependencies-cache-key
          github-dependencies-cache-path
          github-dependencies-cache-restore-keys

    - id: resolve-path
      name: Resolve Cache Path
      shell: bash
      env:
        INPUT_DSB_BUILD_ENVS: ${{ inputs.dsb-build-envs }}
        GITHUB_WORKSPACE: ${{ github.workspace }}
      run: |
        deno run \
          --allow-read --allow-env --allow-write \
          ${{ github.action_path }}/action/1_resolve_path.ts

    - id: recreate-dir
      uses: dsb-norge/directory-recreate@v1
      with:
        directory: ${{ steps.resolve-path.outputs.cache-abs-path }}

    - id: cache-restore
      uses: actions/cache/restore@v4
      with:
        path: ${{ steps.resolve-path.outputs.cache-abs-path }}
        key: ${{ fromJSON(inputs.dsb-build-envs).github-dependencies-cache-key }}
        restore-keys: ${{ fromJSON(inputs.dsb-build-envs).github-dependencies-cache-restore-keys }}
