name: 'Prune images from ACR'
description: |
  Use Azure CLI to delete no longer needed images from docker registry (ACR).
author: 'Direktoratet for samfunnssikkerhet og beredskap'
inputs:
  dsb-build-envs:
    description: |
      DSB build environment variables JSON.
      Required fields:
        See first step.
      Optional fields:
        acr-service-principal
          If set will be used for logging into Azure CLI. Can be skipped if already logged into ACR.
    required: true
runs:
  using: 'composite'
  steps:
    # we need to verify inputs since they are optional input to create-build-envs action
    # TODO revert to @v3
    - uses: dsb-norge/github-actions/ci-cd/require-build-envs@python-support
      with:
        dsb-build-envs: ${{ inputs.dsb-build-envs }}
        require: |
          docker-image-registry
          docker-image-repo
          application-image-name
          docker-image-prune-keep-min-images
          docker-image-prune-keep-num-days

    # log into Azure CLI with service principal
    - uses: azure/login@v2
      if: inputs.dsb-build-envs && fromJSON(inputs.dsb-build-envs).acr-service-principal != ''
      with:
        creds: ${{ inputs.dsb-build-envs && fromJSON(inputs.dsb-build-envs).acr-service-principal }}
        allow-no-subscriptions: true

    - name: 🦕 Deno install
      shell: bash
      run: deno install
      working-directory: ${{ github.action_path }}/../

    - id: delete-images
      shell: bash
      env:
        INPUT_DSB_BUILD_ENVS: ${{ inputs.dsb-build-envs }}
      run: |
        deno run \
          --allow-read \
          --allow-env=NODE_V8_COVERAGE,LD_LIBRARY_PATH,INPUT_DSB_BUILD_ENVS \
          --allow-run=az \
          ${{ github.action_path }}/action/1_prune_images.ts
