name: 'Collect common DSB CI/CD variables stored as github workflow artifacts'
description: |
  This will collect common DSB build environment variables from previously completed parallel build jobs.
  Build-envs for each job are uploaded as github workflow artifacts in JSON format by the create-build-envs action.
  This action pulls down the JSON files, merges them and returns them as output.
author: 'Direktoratet for samfunnssikkerhet og beredskap'
inputs:
  build-envs-artifact-name-prefix:
    description: Prefix used when naming build envs artifact during upload to github in create-build-envs action.
    default: build-envs
    required: false
outputs:
  json-array:
    description: 'Envs from all build jobs as JSON array.'
    value: ${{ steps.collect-build-envs.outputs.json }}

runs:
  using: 'composite'
  steps:
    - name: 🦕 Deno install
      shell: bash
      run: deno install
      working-directory: ${{ github.action_path }}/../

    # download artifact
    - id: download-artifact
      uses: actions/download-artifact@v4
      with:
        pattern: ${{ inputs.build-envs-artifact-name-prefix }}-*
        merge-multiple: true
        path: ./_collect-build-envs

    # merge json files
    - id: collect-build-envs
      shell: bash
      env:
        DOWNLOAD_PATH: ${{ steps.download-artifact.outputs.download-path }}
      run: deno run --allow-env --allow-read --allow-write ${{ github.action_path }}/action/1_collect_envs.ts
