name: 'Check if deploy of DSB app(s) to static environment is allowed'
description: |
  Performs a check if deploy of one or more DSB apps to a static environment is allowed based on branch rules and input parameters.
  The deploy itself is performed by the action deploy-multiple-to-static, this actions just performs a check.
  The default is that apps can only be deployed to static environment(s) from the application repo default branch.
  This behavior can be modified by setting 'dsb-build-envs.static-deploy-from-default-branch-only' to 'false' (default is 'true') in the calling workflow.
author: 'Peder Schmedling'
inputs:
  dsb-build-envs-array:
    description: |
      DSB build environment variables JSON array.
      Required fields:
        See first step.
      Optional fields:
        None.
    required: true
outputs:
  result:
    description: The result of evaluating if deploy is allowed ('true' or 'false').
    value: ${{ steps.evaluate.outputs.result }}
runs:
  using: 'composite'
  steps:
    # verify required inputs exists for all apps
    # TODO revert to @v3
    - uses: dsb-norge/github-actions/ci-cd/require-build-envs@playwright-e2e
      with:
        dsb-build-envs-array: ${{ inputs.dsb-build-envs-array }}
        require: |
          application-name
          static-deploy-from-default-branch-only
          caller-repo-default-branch
          caller-repo-calling-branch
          caller-repo-is-on-default-branch

    # check what branch we are deploying from
    - id: evaluate
      shell: bash
      env:
        JSON_ARRAY: '${{ inputs.dsb-build-envs-array }}'
      run: |
        # Verify deploy is allowed from calling branch

        set -o allexport; source "${{ github.action_path }}/helpers.sh"; set +o allexport;

        start-group "details"
        IS_ALLOWED='true'

        for OBJ in $(echo "${JSON_ARRAY}" | jq -r '.[] | @base64'); do
          JSON_OBJ="$(_jq '.')"
          IS_DEFAULT_BRANCH_VAL="$(get-val 'caller-repo-is-on-default-branch')"
          ONLY_DEFAULT_ALLOWED_VAL="$(get-val 'static-deploy-from-default-branch-only')"
          log-info "Debug: App='$(get-val 'application-name')', IS_DEFAULT_BRANCH_VAL='${IS_DEFAULT_BRANCH_VAL}', ONLY_DEFAULT_ALLOWED_VAL='${ONLY_DEFAULT_ALLOWED_VAL}'"

          # Use [[ ]] for more robust comparison and check against unquoted true/false
          # Disallow if NOT on default branch AND only default branch deploy is enforced
          if [[ "${IS_DEFAULT_BRANCH_VAL}" != "true" ]] && [[ "${ONLY_DEFAULT_ALLOWED_VAL}" != "false" ]]; then
            log-info "deploy from non-default branch is NOT allowed for the app '$(get-val 'application-name')' because 'dsb-build-envs.static-deploy-from-default-branch-only' is set to '${ONLY_DEFAULT_ALLOWED_VAL}'."
            IS_ALLOWED='false'
          else
            log-info "deploy from non-default branch is allowed for the app '$(get-val 'application-name')'."
          fi
          log-info "Action called from branch '$(get-val 'caller-repo-calling-branch')'"
          log-info "Default branch of repo is '$(get-val 'caller-repo-default-branch')'"
        done # Loop apps
        end-group

        log-info "conclusion: '${IS_ALLOWED}'"
        set-output 'result' "${IS_ALLOWED}"
