name: 'Configure Node.js and build node project'
description: |
  Given the required input this action configures the specified version of node and builds a given project.
  Before npm is invoked the version Node.js specified in 'dsb-build-envs' is installed.
  As for working directory the field 'application-source-path' of 'dsb-build-envs' should point to the base directory of the project.
  E2E-Testing:
    - 'npm-test-e2e'
      - Will run 'npm run test:e2e:ci' as part of the building of the app
author: 'Peder Schmedling'
inputs:
  dsb-build-envs:
    description: |
      DSB build environment variables JSON.
      Required fields:
        See first step.
      Optional fields:
        npm-test-e2e
    required: true
runs:
  using: 'composite'
  steps:
    # verify we have required inputs in order to avoid blank labels/tags
    - uses: dsb-norge/github-actions/ci-cd/require-build-envs@npm-e2e
      with:
        dsb-build-envs: ${{ inputs.dsb-build-envs }}
        require: |
          nodejs-version
          application-source-path

    # set up Node.js
    - uses: actions/setup-node@v1
      with:
        node-version:  ${{ fromJSON(inputs.dsb-build-envs).nodejs-version }}

    # npm install, build
    - shell: bash
      run: |
        BUILD_ENVS=$(cat <<'EOF'
        ${{ inputs.dsb-build-envs }}
        EOF
        )
        
        # Helper functions
        # Get field value from BUILD_ENVS safely
        function get-val { echo "${BUILD_ENVS}" | jq -r --arg name "$1" '.[$name]'; }
        
        echo "build-nodejs-project: Looking for project to build ..."
        WORK_DIR=${{ github.workspace }}/${{ fromJSON(inputs.dsb-build-envs).application-source-path }}
        [ -d "${WORK_DIR}" ] \
          && echo "build-nodejs-project: Found project at '${WORK_DIR}'" \
          || echo "ERROR: build-nodejs-project: given 'application-source-path' does not exist: '${WORK_DIR}'" \
          || exit 1
        pushd "${WORK_DIR}" >/dev/null
        echo "::group::build-nodejs-project: npm ci --ignore-scripts"
        npm ci --ignore-scripts
        echo "::endgroup::"
        echo "::group::build-nodejs-project: npm run lint"
        npm run lint
        echo "::endgroup::"
        if [ ! "$(get-val 'npm-test-e2e')" == 'true' ]; then
          echo "::group::build-nodejs-project: npm run test:e2e:ci"
          npm run test:e2e:ci
          echo "::endgroup::"
        fi
        echo "::group::build-nodejs-project: npm run build"
        npm run build
        echo "::endgroup::"
        popd >/dev/null
