name: 'Tear down ephemeral PR environment in AKS'
description: |
  Removes an application and namespace from ephemeral PR environment.
author: 'Peder Schmedling'
inputs:
  dsb-build-envs:
    description: |
      DSB build environment variables JSON.
      Required fields:
        See first step.
      Optional fields:
        None.
    required: true
runs:
  using: 'composite'
  steps:
    # we need to verify inputs since they are optional input to create-build-envs action
    - uses: dsb-norge/github-actions/ci-cd/require-build-envs@v1
      with:
        dsb-build-envs: ${{ inputs.dsb-build-envs }}
        require: |
          pr-deploy-aks-cluster-name
          pr-deploy-aks-resource-group
          pr-deploy-aks-creds
          pr-deploy-k8s-namespace
          pr-deploy-k8s-application-name

    # require pull request for this action to run
    - shell: bash
      run: |
        # Check if triggered by pull request event

        [ ! '${{ github.event_name }}' == 'pull_request' ] \
          && echo 'ERROR: teardown-pr-environment: This action should only be called by pull request events.' \
          && EXIT_CODE=1 \
          || EXIT_CODE=0
        exit ${EXIT_CODE}

    # set target k8s cluster
    - uses: Azure/aks-set-context@v1
      with:
        creds: ${{ fromJSON(inputs.dsb-build-envs).pr-deploy-aks-creds }}
        cluster-name: ${{ fromJSON(inputs.dsb-build-envs).pr-deploy-aks-cluster-name }}
        resource-group: ${{ fromJSON(inputs.dsb-build-envs).pr-deploy-aks-resource-group }}

    - shell: bash
      run: |
        # Remove helm deployment

        helm uninstall ${{ fromJSON(inputs.dsb-build-envs).pr-deploy-k8s-application-name }} \
          --namespace ${{ fromJSON(inputs.dsb-build-envs).pr-deploy-k8s-namespace }}

    - shell: bash
      run: |
        # Remove namespace

        kubectl delete namespace ${{ fromJSON(inputs.dsb-build-envs).pr-deploy-k8s-namespace }}
