name: 'Test DSB build environment variables for non-zero values'
description: |
  Given DSB build environment variables JSON and a list of variable names, this action will test for existence and empty values of these.
  If one or more of the variables does not exist, this action will fail.
  If one or more of the variables are empty, this action will fail.
author: 'Direktoratet for samfunnssikkerhet og beredskap'
inputs:
  dsb-build-envs:
    description: |
      DSB build environment variables JSON.
      Required fields:
        Depends on 'input.require'.
      Optional fields:
        None.
    default: ''
    required: false
  dsb-build-envs-array:
    description: |
      DSB build environment variables JSON array.
      Required fields:
        Depends on 'input.require'.
      Optional fields:
        None.
    default: ''
    required: false
  require:
    description: 'Newline delimited string of variable names to test.'
    required: true
runs:
  using: 'composite'
  steps:
    - name: 🦕 Deno install
      shell: bash
      run: deno install
      working-directory: ${{ github.action_path }}/../

    - id: check-envs
      shell: bash
      env:
        INPUT_JSON_CONFIG: '${{ inputs.dsb-build-envs }}'
        INPUT_REQUIRED_KEYS: '${{ inputs.require }}'
      run: deno run --allow-env --allow-read "${{ github.action_path }}/action/1_check-envs.ts"
    - id: check-envs-array
      shell: bash
      env:
        INPUT_JSON_CONFIG: '${{ inputs.dsb-build-envs-array }}'
        INPUT_REQUIRED_KEYS: '${{ inputs.require }}'
      run: deno run --allow-env --allow-read "${{ github.action_path }}/action/2_check-envs-array.ts"
