name: "DSB Build and deploy Maven artefact"

# The following variables must available in the github 'vars' context:
#   - vars.ORG_MAVEN_REPO_USERNAME            <-- user with read and write to maven repo
#   - vars.ORG_AZURE_CONTAINER_REGISTRY_USER  <-- username of user with push+pull access to ACR, passed to the azure/docker-login action
#
# The following secrets must be available in the github 'secrets' context:
#   - secrets.ORG_AZURE_CONTAINER_REGISTRY_PASSWORD <-- password of user with push+pull access to ACR, passed to the azure/docker-login action
#   - secrets.ORG_GITHUB_PACKAGES_ADMIN_PAT         <-- GitHub PAT with with scopes [delete:packages, read:packages] in the calling repos organization
#   - secrets.ORG_JASYPT_LOCAL_ENCRYPTOR_PASSWORD   <-- jasypt password for local decryption of secrets during maven operations
#   - secrets.ORG_MAVEN_REPO_TOKEN                  <-- token for maven repo user
#   - secrets.ORG_SONAR_TOKEN                       <-- token for sonar integration

on:
  workflow_call:
    inputs:
      apps:
        type: string
        description: |
          specification of app to build and deploy to artifact repo.
          YAML list (as string) with specifications of applications to build and/or deploy.
          Required fields are:
            - application-name        - string
            - application-type        - string, always 'maven-library'
          For optional fields see possible inputs to the create-build-envs action.
        required: true
      # below are repo-specific settings, not app specific and thus does not belong in 'apps'
      # for explanation of maven artifact pruning configuration see inputs of 'ci-cd/prune-maven-artifacts-in-repo/action.yml'
      # sane defaults are defined but can be overridden pr. repo
      maven-artifacts-release-prune-keep-min-count:
        type: number
        required: false
        default: 20
      maven-artifacts-release-prune-keep-num-days:
        type: number
        required: false
        default: 90
      maven-artifacts-snapshot-prune-keep-min-count:
        type: number
        required: false
        default: 0
      maven-artifacts-snapshot-prune-keep-num-days:
        type: number
        required: false
        default: 30
      maven-artifacts-other-prune-keep-min-count:
        type: number
        required: false
        default: 0
      maven-artifacts-other-prune-keep-num-days:
        type: number
        required: false
        default: 0

jobs:
  create-matrix:
    name: Create build matrix
    runs-on: [self-hosted, dsb-builder, linux, x64]
    defaults:
      run:
        shell: bash
    outputs:
      app-vars-matrix: ${{ steps.create-matrix.outputs.app-vars }}
      applications-version: ${{ steps.create-matrix.outputs.applications-version }}
    steps:
      # The create-app-vars-matrix action requires source code to be available
      - name: 🧹 Clean workspace
        id: clean
        uses: dsb-norge/github-actions/directory-recreate@v2

      - name: ⬇ Checkout working branch
        id: checkout
        uses: actions/checkout@v3

      - name: 🎰 Create app vars build matrix
        id: create-matrix
        uses: dsb-norge/github-actions/ci-cd/create-app-vars-matrix@v2
        with:
          apps: ${{ inputs.apps }}

  build-and-deploy:
    name: Build and deploy to artifact repo
    needs: create-matrix
    runs-on: [self-hosted, dsb-builder, linux, x64]
    strategy:
      matrix: ${{ fromJSON(needs.create-matrix.outputs.app-vars-matrix) }}
    defaults:
      run:
        shell: bash
    steps:
      - name: 🧹 Clean workspace
        id: clean
        uses: dsb-norge/github-actions/directory-recreate@v2

      - name: ⬇ Checkout working branch
        id: checkout
        uses: actions/checkout@v3

      - name: 🎰 Generate DSB build variables
        id: build-env
        uses: dsb-norge/github-actions/ci-cd/create-build-envs@v2
        with:
          app-vars: ${{ toJSON(matrix.app-vars) }}
          github-json: ${{ toJSON(github) }}
          secrets-json: ${{ toJSON(secrets) }}
          vars-json: ${{ toJSON(vars) }}
          sonarqube-token: ${{ secrets.ORG_SONAR_TOKEN }}
          jasypt-password: ${{ secrets.ORG_JASYPT_LOCAL_ENCRYPTOR_PASSWORD }}
          github-repo-token: ${{ secrets.GITHUB_TOKEN }}
          acr-username: ${{ vars.ORG_AZURE_CONTAINER_REGISTRY_USER }}
          acr-password: ${{ secrets.ORG_AZURE_CONTAINER_REGISTRY_PASSWORD }}

      - name: "⚒ Library: Build and analyze with Maven"
        id: maven-build
        if: |
          ! ( github.event_name == 'pull_request' && github.event.action == 'closed' )
          && matrix.app-vars.application-type == 'maven-library'
        uses: dsb-norge/github-actions/ci-cd/build-maven-project@v2
        with:
          dsb-build-envs: ${{ steps.build-env.outputs.json }}

  prune-maven-artifacts:
    name: Prune maven artifacts
    # This job handles pruning of maven artifacts published in the calling repo
    # Run even in case of failure in previous jobs/steps, in an attempt to avoid scenarios where PR snapshots would not get deleted
    # Skip step for pull request except to clean up snapshots when closing a PR
    if: >-
      ( success() || failure() )
      &&
      ( github.event_name != 'pull_request' || github.event.action == 'closed' )
    needs: [create-matrix, build-and-deploy]
    runs-on: [self-hosted, dsb-builder, linux, x64]
    defaults:
      run:
        shell: bash
    steps:
      - name: 🗑 Prune maven artifacts
        id: prune
        # This check is required to block deploys when workflow is manually triggered from a non-default branch
        uses: dsb-norge/github-actions/ci-cd/prune-maven-artifacts-in-repo@v2
        with:
          github-packages-token: ${{ secrets.ORG_GITHUB_PACKAGES_ADMIN_PAT }}
          other-prune-keep-min-count: ${{ inputs.maven-artifacts-other-prune-keep-min-count }}
          other-prune-keep-num-days: ${{ inputs.maven-artifacts-other-prune-keep-num-days }}
          release-prune-keep-min-count: ${{ inputs.maven-artifacts-release-prune-keep-min-count }}
          release-prune-keep-num-days: ${{ inputs.maven-artifacts-release-prune-keep-num-days }}
          snapshot-prune-keep-min-count: ${{ inputs.maven-artifacts-snapshot-prune-keep-min-count }}
          snapshot-prune-keep-num-days: ${{ inputs.maven-artifacts-snapshot-prune-keep-num-days }}

  # create a global result indicating if workflow steps succeeded or not,
  # handy for branch protection rules
  ci-cd-conclusion:
    if: always()
    name: ci-cd-conclusion
    needs: [create-matrix, build-and-deploy, prune-maven-artifacts]
    runs-on: [self-hosted, dsb-builder, linux, x64]
    defaults:
      run:
        shell: bash
    steps:
      - run: exit 1
        # for explanation of '>-' below see https://stackoverflow.com/a/67532120/4907315
        # job 'result': possible values are 'success', 'failure', 'cancelled', or 'skipped'
        if: >-
          ${{
               contains(needs.*.result, 'failure')
            || contains(needs.*.result, 'cancelled')
          }}
